### ISSUE TITLE
Faixa cinza na barra de governo

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.paginadestaque#8]
Quando utilizamos o tema `Página de Destaque - Tema Cinza` e o produto `brasil.gov.barra` está instalado, fica uma faixa cinza em cima da barra do governo:

![ss1047845_barracinza](https://cloud.githubusercontent.com/assets/8203476/18559773/3afe5190-7b4f-11e6-9dfb-db0d54509c8c.png)

Isso ocorre porque a barra do governo possui uma [tag nav](https://github.com/govbr/barra.govbr/blob/c84c6e69fc1cc58cf66cca98e707858c73ab2cc2/recipes/default/assets/conteudo-barra_i18n.html#L1) e o tema cinza possui um [css para essa tag](https://github.com/plonegovbr/brasil.gov.paginadestaque/blob/da61c3bfc1ddd3a67905fcd2db62d97d0cb0378e/src/brasil/gov/paginadestaque/themes/destaques-cinza/style.css#L79-L88).

Esse css precisa ficar mais específico para ser aplicado somente no [nav do paginadestaque](https://github.com/plonegovbr/brasil.gov.paginadestaque/blob/85c7edd88be19d4f133a801cf07a2ae13faedf28/src/brasil/gov/paginadestaque/themes/destaques-cinza/index.html#L100).

**Comment by shogunbr** [comment]
@idgserpro : fiz uma correção no CSS do Tema Cinza para funcionar com a versão mais recente do brasil.gov.barra.
Nunca usei o Github para colaborar. Qual é o procedimento? É só eu fazer um pull request para vcs analisarem?
https://github.com/plonegovbr/brasil.gov.paginadestaque/compare/master...shogunbr:issue-8?expand=1

**Comment by idgserpro** [comment]
Sim, basta um PR. 

Se estiver com dúvidas sobre o que colocar no PR, temos esse checklist para PR's https://github.com/plonegovbr/brasil.gov.portal/blob/master/.github/PULL_REQUEST_TEMPLATE.md. Ao longo da revisão você pode ir alterando o PR, por isso recomendamos uma branch separada.

Esse processo de checklist é novo, portanto ainda não colocamos em todos os pacotes e obviamente ele está sujeito a melhorias, temos muito interesse de ouvir opiniões de novatos.

@rodfersou @hvelarde p/c.
